This was fairly simple until clippy went mad about dead code:
error: unreachable pattern
   --> nat/src/lib.rs:728:25
    |
727 |                         IpAddress::Ipv4(a) => a,
    |                         ------------------ matches all the relevant values
728 |                         _ => continue,
    |                         ^ no value can reach this
    |
    = note: `-D unreachable-patterns` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(unreachable_patterns)]`

error: unreachable pattern
   --> nat/src/lib.rs:757:13
    |
756 |             IpAddress::Ipv4(a) => a,
    |             ------------------ matches all the relevant values
757 |             _ => return Ok(()),
    |             ^ no value can reach this

error: irrefutable `if let` pattern
   --> nat/src/lib.rs:794:36
    |
794 |                 let mac_match = if let IpAddress::Ipv4(mac_ipv4) = entry.local_endpoint.addr {
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this pattern will always match, so the `if let` is useless
    = help: consider replacing the `if let` with a `let`
    = note: `-D irrefutable-let-patterns` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(irrefutable_let_patterns)]`

error: irrefutable `if let` pattern
   --> nat/src/lib.rs:800:39
    |
800 |                 let remote_match = if let IpAddress::Ipv4(remote_ipv4) = entry.remote_endpoint.addr
    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this pattern will always match, so the `if let` is useless
    = help: consider replacing the `if let` with a `let`

error: irrefutable `if let` pattern
   --> nat/src/lib.rs:901:24
    |
901 |                       if let (IpAddress::Ipv4(mac_ip), IpAddress::Ipv4(remote_ip)) =
    |  ________________________^
902 | |                         (entry.local_endpoint.addr, entry.remote_endpoint.addr)
    | |_______________________________________________________________________________^
    |
    = note: this pattern will always match, so the `if let` is useless
    = help: consider replacing the `if let` with a `let`

error: irrefutable `if let` pattern
   --> nat/src/lib.rs:916:24
    |
916 |                       if let (IpAddress::Ipv4(mac_ip), IpAddress::Ipv4(remote_ip)) =
    |  ________________________^
917 | |                         (entry.local_endpoint.addr, entry.remote_endpoint.addr)
    | |_______________________________________________________________________________^
    |
    = note: this pattern will always match, so the `if let` is useless
    = help: consider replacing the `if let` with a `let`

error: unreachable pattern
    --> nat/src/lib.rs:1162:37
     |
1161 | ...                   IpAddress::Ipv4(ip) => std::net::IpAddr::V4(ip),
     |                       ------------------- matches all the relevant values
1162 | ...                   _ => {
     |                       ^ no value can reach this

error: could not compile `snow_nat` (lib) due to 7 previous errors

Had to remove a couple of if let to make clippy happy. It makes sense as since there is no IPv6 left it's not possible anything else than that in the code above.